name: altitude_support_ticket_apps
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen: ^5.8.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
